# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-11 01:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogspost',
            name='subtitle',
            field=models.CharField(default='empty subtitle', max_length=150),
        ),
    ]
