# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-14 01:32
from __future__ import unicode_literals

import DjangoUeditor.DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170812_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogspost',
            name='body',
            field=DjangoUeditor.DjangoUeditor.models.UEditorField(blank=True, verbose_name='内容\t'),
        ),
    ]
