# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-18 03:04
from __future__ import unicode_literals

import DjangoUeditor.DjangoUeditor.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0005_blogspost_creator'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', DjangoUeditor.DjangoUeditor.models.UEditorField(blank=True, verbose_name='内容\t')),
                ('boundUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra', to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
    ]
